---
- hosts: server
  gather_facts: false
  tasks:
    - name: Stop EC2 instance
      ec2:
         instance_ids: i-0f3da4f627ff94085
         region: us-west-1
         state: stopped
         wait: True
         vpc_subnet_id: subnet-4468c91e
         assign_public_ip: yes
